### ISSUE TITLE
toJS returns edn string

### ISSUE THREAD

**Issue by Eschon** [shaunxcode/jsedn#22]
I have the following edn string:

`var edn = '{"items" [{"title" "Test" "type" "test"}]}'`

When I use `jsedn.toJS(edn)` I just get the edn string back instead of a JavaScript object

**Comment by josh-stevens** [comment]
Hey man, I know you opened this issue a long time ago, so you probably figured this much out.

You need to do jsedn.toJS(jsedn.parse(edn));

jsedn.parse() will turn the EDN string into nested EDN objects defined by the library. jsedn.toJS() will then take nested EDN objects and turn them into primitive JS collections (arrays/maps).

Yeah it threw me for a loop too, honestly thinking about just writing my own version of this lib, it doesn't really behave the way I want it to.

**Comment by Eschon** [comment]
Thanks for your answer I'll keep it in mind if I ever need this again but I'm not even sure anymore for what I needed this, but I think I just used another similar library.
