### ISSUE TITLE
Using Jest test suite, unable to find type module

### ISSUE THREAD

**Issue by jomendoz** [shaunxcode/jsedn#42]
I started migrating my test suite from Mocha to Jest for a web server and I use `jsedn` in some places.

When I made the change, it threw an error that it cannot find module `type`.

Jest automatically provides a global object `window` that make support for FrontEnd testing in Node.js but I guess it does not automatically provide `type` module.

I think it's not sufficient to test whether global object `window` is available to assume `type` module is also directly available (in `src/type.coffee`). Maybe, you'd like to use `type-component` uniformly throughout the entire project, I don't know which one would be the best solutions for this.

**Comment by yveslange** [comment]
Bump, same problem for me !

**Comment by jmateo** [comment]
Same here

**Comment by yveslange** [comment]
Hi @shaunxcode, are you still alive ? 

Can you check/accept the PR so we can use Jest with your library ?

Best regards.

**Comment by yveslange** [comment]
You can close this issue. Resolved by: https://github.com/shaunxcode/jsedn/pull/44 and it was merged to master.

**Comment by epoberezkin** [comment]
will close when released, will try to do later today :)
